/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminModal: typeof import('./src/components/admin/AdminModal.vue')['default']
    AIAssistant: typeof import('./src/components/AIAssistant.vue')['default']
    AIAssistantModal: typeof import('./src/components/AIAssistantModal.vue')['default']
    AIAssistantSidebar: typeof import('./src/components/AIAssistantSidebar.vue')['default']
    AiBubble: typeof import('./src/components/common/AiBubble.vue')['default']
    AiBubbleExample: typeof import('./src/components/common/AiBubbleExample.vue')['default']
    AiBubbleStreamExample: typeof import('./src/components/common/AiBubbleStreamExample.vue')['default']
    ArticleCard: typeof import('./src/components/article/ArticleCard.vue')['default']
    ArticleComments: typeof import('./src/components/article/ArticleComments.vue')['default']
    ArticleFilter: typeof import('./src/components/article/ArticleFilter.vue')['default']
    ArticleTitle: typeof import('./src/components/article/ArticleTitle.vue')['default']
    ArticleToc: typeof import('./src/components/article/ArticleToc.vue')['default']
    BaseControlPanel: typeof import('./src/components/composable/BaseControlPanel.vue')['default']
    BaseMetricCard: typeof import('./src/components/composable/BaseMetricCard.vue')['default']
    BaseModal: typeof import('./src/components/composable/BaseModal.vue')['default']
    BatchOperationToolbar: typeof import('./src/components/common/BatchOperationToolbar.vue')['default']
    CommentInput: typeof import('./src/components/article/CommentInput.vue')['default']
    ConfirmDialog: typeof import('./src/components/common/ConfirmDialog.vue')['default']
    DPCanvas: typeof import('./src/components/dp/DPCanvas.vue')['default']
    DPControlPanel: typeof import('./src/components/dp/DPControlPanel.vue')['default']
    DPStatus: typeof import('./src/components/dp/DPStatus.vue')['default']
    FileUpload: typeof import('./src/components/common/FileUpload.vue')['default']
    FormField: typeof import('./src/components/common/FormField.vue')['default']
    FormInput: typeof import('./src/components/common/FormInput.vue')['default']
    GalleryItem: typeof import('./src/components/GalleryItem.vue')['default']
    ImageUpload: typeof import('./src/components/common/ImageUpload.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    OJFilterPanel: typeof import('./src/components/oj/OJFilterPanel.vue')['default']
    OJLanguageSelector: typeof import('./src/components/oj/OJLanguageSelector.vue')['default']
    OJProblemCard: typeof import('./src/components/oj/OJProblemCard.vue')['default']
    OJResultPanel: typeof import('./src/components/oj/OJResultPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCanvas: typeof import('./src/components/search/SearchCanvas.vue')['default']
    SearchControlPanel: typeof import('./src/components/search/SearchControlPanel.vue')['default']
    SearchStatus: typeof import('./src/components/search/SearchStatus.vue')['default']
    SimpleEditor: typeof import('./src/components/common/SimpleEditor.vue')['default']
    SortCanvas: typeof import('./src/components/sort/SortCanvas.vue')['default']
    SortControlPanel: typeof import('./src/components/sort/SortControlPanel.vue')['default']
    SortStatus: typeof import('./src/components/sort/SortStatus.vue')['default']
    SparkAIExample: typeof import('./src/components/common/SparkAIExample.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    VirtualList: typeof import('./src/components/common/VirtualList.vue')['default']
  }
}
